#pragma once
struct BuiltinStation { const char *name; const char *url; };
constexpr BuiltinStation kBuiltinStations[] = {
  {"CNR中国之声","https://ngcdn001.cnr.cn/live/zgzs/index.m3u8"},
  {"CNR经济之声","https://ngcdn002.cnr.cn/live/jjzs/index.m3u8"},
  {"CNR环球资讯","https://radio.0472.org/?id=692"},
  {"CNR音乐之声","https://radio.0472.org/?id=641"},
  {"CNR交通广播","https://radio.0472.org/?id=653"},
  {"CNR文艺之声","https://radio.0472.org/?id=648"},
  {"CNR湾区之声","https://radio.0472.org/?id=645"},
  {"CNR经典音乐","https://radio.0472.org/?id=642"},
  {"CNR台海之声","https://radio.0472.org/?id=643"},
  {"CNR神州之声","https://radio.0472.org/?id=644"},
  {"CNR香港之声","https://radio.0472.org/?id=646"},
  {"CNR民族之声","https://radio.0472.org/?id=647"},
  {"CNR老年之声","https://radio.0472.org/?id=649"},
  {"CNR乡村之声","https://radio.0472.org/?id=654"},
  {"CNR南海之声","https://radio.0472.org/?id=664"},
  {"北京交通广播","http://ls.qingting.fm/live/336.m3u8"},
  {"北京新闻广播","https://lhttp.qtfm.cn/live/339/64k.mp3"},
  {"北京文艺广播","http://ls.qingting.fm/live/333.m3u8"},
  {"北京城市广播","https://brtv-radiolive.rbc.cn/alive/fm1073.m3u8"},
  {"北京体育广播","https://brtv-radiolive.rbc.cn/alive/fm1025.m3u8"},
  {"北京阳光调频","https://lhttp.qtfm.cn/live/5021739/64k.mp3"},
  {"北京经典调频","https://radio.0472.org/?id=1254"},
  {"CRI华语环球","http://sk.cri.cn/hyhq.m3u8"},
  {"CRI环球资讯","https://sk.cri.cn/905.m3u8"},
  {"CRI南海之声","https://sk.cri.cn/nhzs.m3u8"},
  {"CRI英语资讯","http://sk.cri.cn/am846.m3u8"},
  {"RTHK3","https://rthkradio3-live.akamaized.net/hls/live/2040079/radio3/master.m3u8"},
  {"香港电台普通话台","https://rthkradiopth-live.akamaized.net/hls/live/2040082/radiopth/master.m3u8"},
  {"湖南经济广播","https://radio.0472.org/?id=1056"},
  {"湖南新闻频道","https://radio.0472.org/?id=525"},
  {"湖南潇湘之声","https://radio.0472.org/?id=526"},
  {"重庆文艺广播","http://satellitepull.cnr.cn/live/wxcqwygb/playlist.m3u8"},
  {"上海故事广播","http://live.cooltv.top/tv/news1296.php?id=10"},
  {"山西文艺广播","http://radiolive.sxrtv.com/live/wenyi/playlist.m3u8"},
  {"江苏文艺广播","http://satellitepull.cnr.cn/live/wx32jswygb/playlist.m3u8"},
  {"江苏故事广播","http://satellitepull.cnr.cn/live/wx32jsgsgb/playlist.m3u8"},
  {"上海戏曲广播","https://radio.0472.org/?id=1314"},
  {"陕西故事广播","https://radio.0472.org/?id=1133"},
  {"北京音乐广播","http://ls.qingting.fm/live/332.m3u8"},
  {"湖南金鹰之声","https://radio.0472.org/?id=523"},
  {"芒果时空音乐","https://radio.0472.org/?id=524"},
  {"湖南交通广播","https://radio.0472.org/?id=1059"},
  {"湖南音乐之声","https://radio.0472.org/?id=1060"},
  {"长沙交通广播","https://radio.0472.org/?id=1061"},
  {"长沙音乐广播","https://radio.0472.org/?id=1531"},
  {"广东音乐之声","http://ls.qingting.fm/live/1260.m3u8"},
  {"江西音乐广播","http://satellitepull.cnr.cn/live/wx32jiangxyygb/playlist.m3u8"},
  {"河北音乐广播","https://radio.0472.org/?id=381"},
  {"深圳音乐频率","https://radio.0472.org/?id=498"},
  {"南京音乐广播","http://hls.njgb.com/live_hls/4/playlist.m3u8"},
  {"江苏音乐广播","https://radio.0472.org/?id=415"},
  {"河北汽车音乐","https://radio.pull.hebtv.com/live/hebqcyy.m3u8"},
  {"重庆音乐广播","https://radio.0472.org/?id=372"},
  {"龙江音乐广播","https://radio.0472.org/?id=552"},
  {"内蒙音乐之声","https://radio.0472.org/?id=572"},
  {"宁夏音乐广播","https://radio.0472.org/?id=1701"},
  {"陕西音乐广播","https://radio.0472.org/?id=561"},
  {"青海音乐广播","https://radio.0472.org/?id=616"},
  {"山西音乐广播","https://radio.0472.org/?id=637"},
  {"山东音乐广播","https://radio.0472.org/?id=702"},
  {"安徽音乐广播","https://radio.0472.org/?id=601"},
  {"江苏经典流行","http://satellitepull.cnr.cn/live/wx32jsjdlxyy/playlist.m3u8"},
  {"浙江音乐调频","https://radio.0472.org/?id=928"},
  {"厦门音乐广播","https://radio.0472.org/?id=1897"},
  {"云南音乐广播","https://radio.0472.org/?id=592"},
  {"广西音乐台","https://radio.0472.org/?id=590"},
  {"贵州音乐广播","https://radio.0472.org/?id=435"},
  {"新疆音乐广播","https://radio.0472.org/?id=1158"},
  {"海南音乐广播","https://radio.0472.org/?id=543"},
  {"河北文艺广播","http://satellitepull.cnr.cn/live/wxhebwygb/playlist.m3u8"},
  {"RFI 法广中文","https://rfienchinois64k.ice.infomaniak.ch/rfienchinois-64.mp3"},
  {"台湾中广新闻网","https://n03.rcs.revma.com/78fm9wyy2tzuv"},
  {"BBC World Service","http://as-hls-ww-live.akamaized.net/pool_87948813/live/ww/bbc_world_service/bbc_world_service.isml/bbc_world_service-audio%3d96000.norewind.m3u8"},
  {"CNN","https://tunein.cdnstream1.com/3519_96.aac"},
  {"CNA","https://14033.live.streamtheworld.com/938NOW_PREM.aac"},
  {"GB News","https://listen-gbnews.sharp-stream.com/gbnews.mp3"},
  {"LBC News","https://icecast.thisisdax.com/LBCNewsUKMP3"},
  {"Times Radio","http://timesradio.wireless.radio/stream"},
  {"Talk Radio","https://radio.talkradio.co.uk/stream"},
  {"新加坡 CAPITAL 958","https://playerservices.streamtheworld.com/api/livestream-redirect/CAPITAL958FM_PREM.aac"},
  {"Hao FM","https://playerservices.streamtheworld.com/api/livestream-redirect/HAO_963.mp3"},
  {"Gold FM","http://22903.live.streamtheworld.com:3690/GOLD905_PREM.aac"},
  {"Money FM","https://playerservices.streamtheworld.com/api/livestream-redirect/MONEY_893AAC.aac"},
  {"Yes FM","https://22393.live.streamtheworld.com/YES933_PREM.aac"},
  {"Kiss FM","https://playerservices.streamtheworld.com/api/livestream-redirect/KISS_92AAC.aac"},
  {"NPR News","https://nprdmcoitunes.akamaized.net/hls/live/2034276/itls/playlist.m3u8"},
  {"ABC News Radio","https://mediaserviceslive.akamaized.net/hls/live/2038318/rnnsw/masterhq.m3u8"},
  {"Newstalk ZB","https://playerservices.streamtheworld.com/api/livestream-redirect/NZME_31AAC.aac"},
  {"Power FM","https://crystalout.surfernetwork.com:8001/KVSP_MP3"},
  {"Classic FM","https://ice-sov.musicradio.com/ClassicFMMP3"},
  {"BBC Radio 1","http://as-hls-ww-live.akamaized.net/pool_01505109/live/ww/bbc_radio_one/bbc_radio_one.isml/bbc_radio_one-audio%3d96000.norewind.m3u8"},
  {"BBC Radio 1 Xtra","http://as-hls-ww-live.akamaized.net/pool_92079267/live/ww/bbc_1xtra/bbc_1xtra.isml/bbc_1xtra-audio%3d96000.norewind.m3u8"},
  {"BBC Radio 1 Dance","http://as-hls-ww-live.akamaized.net/pool_62063831/live/ww/bbc_radio_one_dance/bbc_radio_one_dance.isml/bbc_radio_one_dance-audio%3d96000.norewind.m3u8"},
  {"BBC Radio 2","http://as-hls-ww-live.akamaized.net/pool_74208725/live/ww/bbc_radio_two/bbc_radio_two.isml/bbc_radio_two-audio%3d96000.norewind.m3u8"},
  {"BBC Radio 3","http://as-hls-ww-live.akamaized.net/pool_23461179/live/ww/bbc_radio_three/bbc_radio_three.isml/bbc_radio_three-audio%3d96000.norewind.m3u8"},
  {"BBC Radio 4","http://as-hls-ww-live.akamaized.net/pool_55057080/live/ww/bbc_radio_fourfm/bbc_radio_fourfm.isml/bbc_radio_fourfm-audio%3d96000.norewind.m3u8"},
  {"BBC Radio 4 Extra","http://as-hls-ww-live.akamaized.net/pool_26173715/live/ww/bbc_radio_four_extra/bbc_radio_four_extra.isml/bbc_radio_four_extra-audio%3d96000.norewind.m3u8"},
  {"BBC Radio 5 Live","http://as-hls-ww-live.akamaized.net/pool_89021708/live/ww/bbc_radio_five_live/bbc_radio_five_live.isml/bbc_radio_five_live-audio%3d96000.norewind.m3u8"},
  {"BBC Radio 6 Music","http://as-hls-ww-live.akamaized.net/pool_81827798/live/ww/bbc_6music/bbc_6music.isml/bbc_6music-audio%3d96000.norewind.m3u8"},
  {"BBC Radio Asian Network","http://as-hls-ww-live.akamaized.net/pool_22108647/live/ww/bbc_asian_network/bbc_asian_network.isml/bbc_asian_network-audio%3d96000.norewind.m3u8"},
  {"凤凰卫视中文台","https://playtv-live.ifeng.com/live/06OLEGEGM4G_audio.m3u8"},
  {"CCTV-13 新闻伴音","https://piccpndali.v.myalicdn.com/audio/cctv13_2.m3u8"},
  {"上海新闻广播","https://satellitepull.cnr.cn/live/wx32shrmgb/playlist.m3u8"},
  {"上海第一财经广播","https://lhttp.qtfm.cn/live/276/64k.mp3"},
  {"江苏新闻广播","https://satellitepull.cnr.cn/live/wx32jsxwgb/playlist.m3u8"},
  {"浙江之声","https://satellitepull.cnr.cn/live/wxzjzs/playlist.m3u8"},
  {"广东新闻广播","https://satellitepull.cnr.cn/live/wxgdxwgb/playlist.m3u8"},
  {"广东珠江经济电台","https://lhttp.qtfm.cn/live/1259/64k.mp3"},
  {"四川综合广播","https://satellitepull.cnr.cn/live/wxsczhgb/playlist.m3u8"},
  {"香港电台第一台","https://rthkradio1-live.akamaized.net/hls/live/2035313/radio1/master.m3u8"},
  {"台湾中央广播电台","https://streamak0138.akamaized.net/live0138lh-mbm9/_definst_/rti3/chunklist.m3u8"},
  {"台湾 News98","https://n17a-eu.rcs.revma.com/pntx1639ntzuv"},
  {"马来西亚 Ai FM","https://playerservices.streamtheworld.com/api/livestream-redirect/AI_FMAAC_SC"},
};
constexpr size_t kBuiltinStationCount = sizeof(kBuiltinStations) / sizeof(kBuiltinStations[0]);
